Repository opensafely-core/job-server, pull requests merged in 2021-11, with the labels that each got.

#1235 Update JS dependencies
  package-lock.json
  package.json
Labels: dependencies, javascript

#1238 Replace JS dependencies
  .swcrc
  assets/src/scripts/outputs-viewer/hooks/use-window-size.js
  babel.config.js
  jest.config.js
  package-lock.json
  package.json
Labels: enhancement, dependencies, javascript

#1250 Replace Zustand with React Context
  assets/src/scripts/outputs-viewer/App.jsx
  assets/src/scripts/outputs-viewer/components/Button/PrepareButton.jsx
  assets/src/scripts/outputs-viewer/components/Button/PublishButton.jsx
  assets/src/scripts/outputs-viewer/components/FileList/FileList.jsx
  assets/src/scripts/outputs-viewer/components/Iframe/Iframe.jsx
  assets/src/scripts/outputs-viewer/components/NoPreview/NoPreview.jsx
  assets/src/scripts/outputs-viewer/components/Viewer/Viewer.jsx
  assets/src/scripts/outputs-viewer/components/Viewer/Wrapper.jsx
  assets/src/scripts/outputs-viewer/context/FilesProvider.jsx
  assets/src/scripts/outputs-viewer/hooks/use-file-list.js
  assets/src/scripts/outputs-viewer/hooks/use-file.js
  assets/src/scripts/outputs-viewer/index.jsx
  assets/src/scripts/outputs-viewer/stores/use-store.js
  assets/src/scripts/outputs-viewer/tests/App.test.jsx
  assets/src/scripts/outputs-viewer/tests/__mocks__/zustand.js
  assets/src/scripts/outputs-viewer/tests/components/Button/PrepareButton.test.jsx
  assets/src/scripts/outputs-viewer/tests/components/Button/PublishButton.test.jsx
  assets/src/scripts/outputs-viewer/tests/components/FileList/FileList.test.jsx
  assets/src/scripts/outputs-viewer/tests/components/Iframe/Iframe.test.jsx
  assets/src/scripts/outputs-viewer/tests/components/NoPreview/NoPreview.test.jsx
  assets/src/scripts/outputs-viewer/tests/components/Table/Table.test.jsx
  assets/src/scripts/outputs-viewer/tests/components/Viewer/Viewer.test.jsx
  assets/src/scripts/outputs-viewer/tests/test-utils.jsx
  jest.config.js
  package-lock.json
  package.json
Labels: enhancement, javascript

#1275 Revert "Replace base64 image with URL"
  assets/src/scripts/outputs-viewer/hooks/use-file.js
  assets/src/scripts/outputs-viewer/tests/components/Viewer/Viewer.test.jsx
Labels: frontend

#1302 Update JS dependencies
  .swcrc
  assets/src/scripts/outputs-viewer/components/Viewer/Wrapper.jsx
  assets/src/scripts/outputs-viewer/context/FilesProvider.jsx
  assets/src/scripts/outputs-viewer/tests/components/FileList/FileList.test.jsx
  babel.config.js
  jest.config.js
  package-lock.json
  package.json
Labels: dependencies, javascript

#1323 Update terms.md
  snippets/terms.md
Labels: application-process

#1324 Update 1-rubric.md
  snippets/1-rubric.md
Labels: application-process

#1325 Update 2-rubric.md
  snippets/2-rubric.md
Labels: application-process

#1328 Update form_specs.py
  applications/form_specs.py
Labels: application-process

#1329 Create patient-level.md
  snippets/patient-level.md
Labels: application-process

#1331 Update datasets-rubric.md
  snippets/datasets-rubric.md
Labels: application-process

#1332 Create emis_justification.md
  snippets/6-rubric.md
  snippets/emis_justification.md
Labels: application-process

#1334 Update apply.html
  applications/templates/applications/apply.html
Labels: application-process

#1335 Update references-rubric.md
  snippets/references-rubric.md
Labels: application-process

#1330 Update form_specs.py
  applications/form_specs.py
Labels: application-process

#1333 Update form_specs.py
  applications/form_specs.py
Labels: application-process

#1336 Update form_specs.py
  applications/form_specs.py
Labels: application-process

#1345 Update apply.html
  applications/templates/applications/apply.html
Labels: application-process

#1347 Update terms.md
  snippets/terms.md
Labels: application-process

#1348 Update 1-rubric.md
  snippets/1-rubric.md
Labels: application-process

#1349 Update patient-level.md
  snippets/patient-level.md
Labels: application-process

#1351 Update emis_justification.md
  snippets/emis_justification.md
Labels: application-process

#1350 Update datasets-rubric.md
  snippets/datasets-rubric.md
Labels: application-process

#1346 Update start_page.md
  snippets/start_page.md
Labels: application-process

#1352 Create service-evaluation-audit-footer.md
  snippets/service-evaluation-audit-footer.md
Labels: application-process

#1353 Update service-evaluation-audit-rubric.md
  snippets/service-evaluation-audit-rubric.md
Labels: application-process

#1355 Update 16-rubric.md
  snippets/16-rubric.md
Labels: application-process

#1363 Update 16-rubric.md
  snippets/16-rubric.md
Labels: application-process

#1367 Update service-evaluation-audit-footer.md
  snippets/service-evaluation-audit-footer.md
Labels: application-process

#1398 Update JS dependencies
  package-lock.json
  package.json
Labels: dependencies, javascript
