Repository opensafely-core/job-server, pull requests merged in 2021-12, with the labels that each got.

#1421 Replace convertBlobToBase64 with createObjectURL
  assets/src/scripts/outputs-viewer/hooks/use-file.js
  assets/src/scripts/outputs-viewer/tests/components/Viewer/Viewer.test.jsx
  assets/src/scripts/outputs-viewer/tests/jest-setup.js
Labels: javascript

#1427 Update start_page.md
  snippets/start_page.md
Labels: application-process

#1439 Update JS dependencies
  package-lock.json
  package.json
  vite.config.js
Labels: dependencies, javascript

#1446 Update terms.md
  snippets/terms.md
Labels: application-process

#1458 Update JS dependencies
  package-lock.json
  package.json
Labels: dependencies, javascript

#1459 Add sourcemaps to Vite compiled assets
  jobserver/settings.py
  vite.config.js
Labels: frontend
