Repository opensafely-core/job-server, pull requests merged in 2023-08, with the labels that each got.

#3356 Move Outputs SPA and linked templates to Tailwind
  assets/src/scripts/outputs-viewer/App.jsx
  assets/src/scripts/outputs-viewer/__tests__/App.test.jsx
  assets/src/scripts/outputs-viewer/__tests__/components/FileList/FileList.test.jsx
  assets/src/scripts/outputs-viewer/__tests__/components/NoPreview/NoPreview.test.jsx
  assets/src/scripts/outputs-viewer/__tests__/components/Toast/Toast.test.jsx
  assets/src/scripts/outputs-viewer/__tests__/components/Viewer/Viewer.test.jsx
  assets/src/scripts/outputs-viewer/__tests__/helpers/files.js
  assets/src/scripts/outputs-viewer/__tests__/hooks/use-file-list.test.js
  assets/src/scripts/outputs-viewer/__tests__/test-utils.jsx
  assets/src/scripts/outputs-viewer/components/Button/Button.jsx
  assets/src/scripts/outputs-viewer/components/Button/PrepareButton.jsx
  assets/src/scripts/outputs-viewer/components/Button/PublishButton.jsx
  assets/src/scripts/outputs-viewer/components/Card/index.jsx
  assets/src/scripts/outputs-viewer/components/FileList/FileList.jsx
  assets/src/scripts/outputs-viewer/components/FileList/Filter.jsx
  assets/src/scripts/outputs-viewer/components/Form/Input.jsx
  assets/src/scripts/outputs-viewer/components/Image/Image.jsx
  assets/src/scripts/outputs-viewer/components/Link/index.jsx
  assets/src/scripts/outputs-viewer/components/Metadata/Metadata.jsx
  assets/src/scripts/outputs-viewer/components/NoPreview/NoPreview.jsx
  assets/src/scripts/outputs-viewer/components/Table/Table.jsx
  assets/src/scripts/outputs-viewer/components/Text/Text.jsx
  assets/src/scripts/outputs-viewer/components/Toast/Toast.jsx
  assets/src/scripts/outputs-viewer/hooks/use-file-list.js
  assets/src/scripts/outputs-viewer/index.jsx
  assets/src/styles/outputs-viewer.scss
  package-lock.json
  package.json
  templates/outputs-spa.html
  templates/release_detail.html
  templates/snapshot_detail.html
  templates/workspace_backend_files.html
  templates/workspace_latest_outputs_detail.html
Labels: restyle, deck-scrubbing

#3361 Fixes for the Outputs SPA
  assets/src/scripts/outputs-viewer/App.jsx
  assets/src/scripts/outputs-viewer/components/FileList/FileList.jsx
  assets/src/scripts/outputs-viewer/components/Iframe/Iframe.jsx
  assets/src/scripts/outputs-viewer/components/Metadata/Metadata.jsx
  assets/src/scripts/outputs-viewer/components/Table/Table.jsx
  templates/snapshot_detail.html
Labels: restyle, deck-scrubbing

#3362 Fixes for spacing and padding in SPA
  assets/src/scripts/outputs-viewer/App.jsx
  assets/src/scripts/outputs-viewer/components/Table/Table.jsx
  templates/_components/breadcrumbs/breadcrumb.html
  templates/release_detail.html
  templates/snapshot_detail.html
  templates/workspace_backend_files.html
  templates/workspace_latest_outputs_detail.html
Labels: restyle, deck-scrubbing

#3364 JS pipeline tweaks
  assets/src/fonts/public-sans-v5-latin-500.woff
  assets/src/fonts/public-sans-v5-latin-500.woff2
  assets/src/fonts/public-sans-v5-latin-600.woff
  assets/src/fonts/public-sans-v5-latin-600.woff2
  assets/src/fonts/public-sans-v5-latin-700.woff
  assets/src/fonts/public-sans-v5-latin-700.woff2
  assets/src/fonts/public-sans-v5-latin-regular.woff
  assets/src/fonts/public-sans-v5-latin-regular.woff2
  assets/src/scripts/tw.js
  assets/src/styles/_fonts.scss
  assets/src/styles/main.scss
  assets/src/styles/tw.css
  docker/Dockerfile
  jobserver/settings.py
  package-lock.json
  package.json
  postcss.config.js
  postcss.config.mjs
  tailwind.config.mjs
  vite.config.mjs
Labels: dependencies, javascript, deck-scrubbing

#3367 Fix font CSP setting
  jobserver/settings.py
Labels: deck-scrubbing

#3369 Switch templates to Tailwind styles
  assets/src/scripts/sign-off-repo.js
  templates/_components/article/header.html
  templates/_components/form/input.html
  templates/_components/form/textarea.html
  templates/sign_off_repo.html
  templates/workspace_create.html
  templates/workspace_create_error.html
  templates/workspace_log.html
  vite.config.mjs
Labels: restyle, deck-scrubbing

#3442 Set up Staff Area template using new styles
  assets/src/scripts/staff-tw.js
  assets/src/styles/staff-tw.css
  templates/_components/article/header.html
  templates/_components/card/card.html
  templates/_components/form/input.html
  templates/_components/header.html
  templates/base-tw.html
  templates/staff/base-tw.html
  templates/staff/index.html
  vite.config.mjs
Labels: restyle, deck-scrubbing

#3450 Update the Sentry Staff Area templates
  templates/_components/breadcrumbs/breadcrumb.html
  templates/_components/list-group/list-group.html
  templates/_partials/staff-hero.html
  templates/components.yaml
  templates/staff/index.html
  templates/staff/sentry/index.html
  templates/staff/sentry/message.html
Labels: restyle

#3458 Restyle Staff Backend section
  staff/views/backends.py
  templates/staff/backend/create.html
  templates/staff/backend/detail.html
  templates/staff/backend/edit.html
  templates/staff/backend/list.html
  templates/staff/backend_create.html
  templates/staff/backend_detail.html
  templates/staff/backend_edit.html
  templates/staff/backend_list.html
Labels: restyle

#3456 Run docker image as non-root user
  .gitignore
  docker/Dockerfile
  docker/docker-compose.yaml
  docker/justfile
  docker/staticfiles/.keep
  scripts/collect-me-maybe.sh
Labels: security
