Repository opensafely-core/job-server, pull requests merged in 2024-01, with the labels that each got.

#3906 Update JavaScript dependencies
  package-lock.json
  package.json
Labels: dependencies, javascript

#3954 Update JS dependencies
  package-lock.json
  package.json
Labels: dependencies, javascript

#3985 Update JS dependencies
  package-lock.json
  package.json
Labels: dependencies, javascript

#3995 Fix logout link
  templates/_components/header.html
  templates/base.html
Labels: bug

#3571 Convert Project.org to an M2M
  interactive/commands.py
  jobserver/api/jobs.py
  jobserver/migrations/0013_add_project_orgs.py
  jobserver/migrations/0014_copy_project_org_to_orgs.py
  jobserver/migrations/0015_remove_project_org.py
  jobserver/models/__init__.py
  jobserver/models/project.py
  jobserver/models/project_collaboration.py
  jobserver/views/index.py
  jobserver/views/job_requests.py
  jobserver/views/orgs.py
  jobserver/views/projects.py
  jobserver/views/users.py
  jobserver/views/workspaces.py
  staff/forms.py
  staff/views/applications.py
  staff/views/dashboards/copiloting.py
  staff/views/dashboards/projects.py
  staff/views/job_requests.py
  staff/views/projects.py
  staff/views/reports.py
  staff/views/repos.py
  staff/views/workspaces.py
  templates/staff/dashboards/projects.html
  templates/staff/project/detail.html
  templates/staff/project/edit.html
  templates/staff/repo/list.html
  tests/factories/jobserver.py
  tests/unit/interactive/test_commands.py
  tests/unit/jobserver/api/test_jobs.py
  tests/unit/jobserver/models/test_project_collaboration.py
  tests/unit/jobserver/models/test_user.py
  tests/unit/jobserver/models/test_workspace.py
  tests/unit/jobserver/views/test_job_requests.py
  tests/unit/jobserver/views/test_orgs.py
  tests/unit/jobserver/views/test_projects.py
  tests/unit/jobserver/views/test_repos.py
  tests/unit/jobserver/views/test_users.py
  tests/unit/jobserver/views/test_workspaces.py
  tests/unit/staff/test_forms.py
  tests/unit/staff/views/test_applications.py
  tests/unit/staff/views/test_job_requests.py
  tests/unit/staff/views/test_projects.py
  tests/unit/staff/views/test_reports.py
  tests/unit/staff/views/test_repos.py
  tests/unit/staff/views/test_users.py
  tests/unit/staff/views/test_workspaces.py
Labels: deck-scrubbing

#4011 Update npm dependencies
  package-lock.json
  package.json
Labels: dependencies, javascript

#4055 Update JS dependencies
  package-lock.json
  package.json
Labels: dependencies, javascript
